name: Build Project (for Launchpad PPA)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install required packages
        run: |
          sudo apt install curl locales-all cli-common-dev libunwind8-dev libcurl4-openssl-dev rustc cargo devscripts debhelper-compat dput
        
      - name: Initialize offline package
        run: |
          sudo ip netns add no-net
        
      - name: Try to build
        run: |
          sudo ip netns exec no-net make debian-all-offline
