name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: NuGlobal artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: ng-build-linux
        path: "target/debug/"

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: NuGlobal artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: ng-build-windows
        path: "target/debug/"

  notify:

    runs-on: ubuntu-latest
    needs:
      - build-ubuntu
      - build-windows
    if: ${{ always() }}
    
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.G_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
